### ISSUE TITLE
putget_test:TestPutGet intermittent failures

### ISSUE THREAD

**Issue by mambocab** [riptano/cassandra-dtest#170]
I get intermittent failures running [putget_test.TestPutGet](https://github.com/riptano/cassandra-dtest/blob/master/putget_test.py#L11). Here are two gists with the stdout and stderr from failing runs:

https://gist.github.com/mambocab/b724a2c697416f21a621
https://gist.github.com/mambocab/adb5cb90c14cda5f87c8

and here are the same for a successful run:

https://gist.github.com/mambocab/de2a089e93bc4dff61cc

There's some noise about reading JMX metrics in the Java stack traces that can be ignored for this issue. This is in the traces for both failing runs, and not in the trace for the successful one:

```
java.lang.AssertionError: org.apache.cassandra.exceptions.AlreadyExistsException: Cannot add already existing table "resource_role_permissons_index" to keyspace "system_auth"
    at org.apache.cassandra.service.StorageService.doAuthSetup(StorageService.java:897)
    at org.apache.cassandra.service.StorageService.joinTokenRing(StorageService.java:832)
    at org.apache.cassandra.service.StorageService.initServer(StorageService.java:579)
    at org.apache.cassandra.service.StorageService.initServer(StorageService.java:469)
    at org.apache.cassandra.service.CassandraDaemon.setup(CassandraDaemon.java:357)
    at org.apache.cassandra.service.CassandraDaemon.activate(CassandraDaemon.java:492)
    at org.apache.cassandra.service.CassandraDaemon.main(CassandraDaemon.java:599)
Caused by: org.apache.cassandra.exceptions.AlreadyExistsException: Cannot add already existing table "resource_role_permissons_index" to keyspace "system_auth"
    at org.apache.cassandra.service.MigrationManager.announceNewColumnFamily(MigrationManager.java:286)
    at org.apache.cassandra.service.MigrationManager.announceNewColumnFamily(MigrationManager.java:275)
    at org.apache.cassandra.service.StorageService.doAuthSetup(StorageService.java:891)
    ... 6 more
```

The test command is

```
STAMP=$(date +%y-%m-%d-%H.%M.%S) CASSANDRA_DIR=~/cstar_src/cassandra PRINT_DEBUG=true nosetests -x -s -v putget_test:TestPutGet >~/putget_test_$STAMP.stdout 2>~/putget_test_$STAMP.stderr
```

I'm running in Ubuntu under VirtualBox with 2GB of memory, which may be the problem.

```
$ uname -a
Linux dtest-VirtualBox 3.13.0-45-generic #74-Ubuntu SMP Tue Jan 13 19:36:28 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by ptnapoleon** [comment]
This is probably enough information to turn into a Jira ticket. What C* version is this? If it's trunk, assign it to Sam Tunnicliffe.

**Comment by mambocab** [comment]
It's trunk. Reproduced it with 4GB of memory:

https://gist.github.com/mambocab/b724a2c697416f21a621

I think it might be a dtest-related error, because

- [this run](https://gist.github.com/mambocab/adb5cb90c14cda5f87c8#file-putget_test_15-02-19-16-46-49-stderr) and [this run](https://gist.github.com/mambocab/b724a2c697416f21a621#file-putget_test-stderr) failed on different tests.
- the failure report is consistent with [a bad teardown](https://gist.github.com/mambocab/adb5cb90c14cda5f87c8#file-putget_test_15-02-19-16-46-49-stderr-L26) that left behind a [table that another test tried to add](https://gist.github.com/mambocab/adb5cb90c14cda5f87c8#file-putget_test_15-02-19-16-46-49-stdout-L217).

Should I do more dtest digging, or does this still look like one for Jira?

**Comment by ptnapoleon** [comment]
I think it's for Jira. We aren't adding that table, that's internal stuff going on to set up a new node. I don't see anything wrong with the test logic after a quick look

**Comment by mambocab** [comment]
This is being worked on here:

https://issues.apache.org/jira/browse/CASSANDRA-8853

**Comment by mshuler** [comment]
8853 was closed and I haven't seen a recent failure on this test. Closing.
