### ISSUE TITLE
bootstrap_test.TestBootstrap.manual_bootstrap_test fails in 2.0

### ISSUE THREAD

**Issue by mshuler** [riptano/cassandra-dtest#264]
This looks pretty straightforward - capitalization and quoting?:
```
ERROR: manual_bootstrap_test (bootstrap_test.TestBootstrap)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/mshuler/git/cassandra-dtest/bootstrap_test.py", line 196, in manual_bootstrap_test
    original_rows = list(session.execute("SELECT * FROM keyspace1.standard1"))
  File "/home/mshuler/git/python-driver/cassandra/cluster.py", line 1414, in execute
    result = future.result(timeout)
  File "/home/mshuler/git/python-driver/cassandra/cluster.py", line 2997, in result
    raise self._final_exception
InvalidRequest: code=2200 [Invalid query] message="Keyspace keyspace1 does not exist"
```

**Comment by ptnapoleon** [comment]
Fixed at 5e461c34f0c621abd7101c76ead683ef57f25bf2

**Comment by ptnapoleon** [comment]
Still failing on CI for some reason

**Comment by ptnapoleon** [comment]
Passing on CI. Will re-open if becomes intermittent.
