### ISSUE TITLE
paging_test.TestPagingWithDeletions.test_failure_threshold_deletions fails in 2.0

### ISSUE THREAD

**Issue by mshuler** [riptano/cassandra-dtest#265]
```
ERROR: test_failure_threshold_deletions (paging_test.TestPagingWithDeletions)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/mshuler/git/cassandra-dtest/paging_test.py", line 1271, in test_failure_threshold_deletions
    self.cursor = self.prepare()
  File "/home/mshuler/git/cassandra-dtest/paging_test.py", line 177, in prepare
    cursor = self.cql_connection(node1)
  File "/home/mshuler/git/cassandra-dtest/dtest.py", line 259, in cql_connection
    protocol_version)
  File "/home/mshuler/git/cassandra-dtest/dtest.py", line 288, in _create_session
    session = cluster.connect()
  File "/home/mshuler/git/python-driver/cassandra/cluster.py", line 765, in connect
    self.control_connection.connect()
  File "/home/mshuler/git/python-driver/cassandra/cluster.py", line 1877, in connect
    self._set_new_connection(self._reconnect_internal())
  File "/home/mshuler/git/python-driver/cassandra/cluster.py", line 1912, in _reconnect_internal
    raise NoHostAvailable("Unable to connect to any servers", errors)
NoHostAvailable: ('Unable to connect to any servers', {'127.0.0.1': OperationTimedOut('errors=None, last_host=None',)})
```

**Comment by ptnapoleon** [comment]
Failing due to TombstoneOverwhelmingException in the logs

**Comment by knifewine** [comment]
I think triggering that exception is intentional in this case, might just
need to confirm the exception is seen, and that paging works ok/reasonably
when that occurs.

**Comment by ptnapoleon** [comment]
@knifewine Check out #268 and let me know if you think that is legit.
