### ISSUE TITLE
paxos_tests.TestPaxos.replica_availability_test fails in all branches

### ISSUE THREAD

**Issue by mshuler** [riptano/cassandra-dtest#266]
Looks to me like a test problem - it fails in the same way in all branches:
```
ERROR: replica_availability_test (paxos_tests.TestPaxos)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/mshuler/git/cassandra-dtest/paxos_tests.py", line 47, in replica_availability_test
    session.execute("INSERT INTO test (k, v) VALUES (3, 3) IF NOT EXISTS")
  File "/home/mshuler/git/python-driver/cassandra/cluster.py", line 1414, in execute
    result = future.result(timeout)
  File "/home/mshuler/git/python-driver/cassandra/cluster.py", line 2997, in result
    raise self._final_exception
Unavailable: code=1000 [Unavailable exception] message="Cannot achieve consistency level SERIAL" info={'required_replicas': 2, 'alive_replicas': 1, 'consistency': 'SERIAL'}
-------------------- >> begin captured logging << --------------------
dtest: DEBUG: cluster ccm directory: /tmp/dtest-868xh7
cassandra.cluster: WARNING: Host 127.0.0.3 has been marked down
cassandra.pool: WARNING: Error attempting to reconnect to 127.0.0.3, scheduling retry in 2.0 seconds: [Errno 111] Tried connecting to [('127.0.0.3', 9042)]. Last error: Connection refused
cassandra.pool: WARNING: Error attempting to reconnect to 127.0.0.3, scheduling retry in 4.0 seconds: [Errno 111] Tried connecting to [('127.0.0.3', 9042)]. Last error: Connection refused
cassandra.cluster: WARNING: Host 127.0.0.2 has been marked down
cassandra.pool: WARNING: Error attempting to reconnect to 127.0.0.2, scheduling retry in 2.0 seconds: [Errno 111] Tried connecting to [('127.0.0.2', 9042)]. Last error: Connection refused
cassandra.pool: WARNING: Error attempting to reconnect to 127.0.0.2, scheduling retry in 4.0 seconds: [Errno 111] Tried connecting to [('127.0.0.2', 9042)]. Last error: Connection refused
--------------------- >> end captured logging << ---------------------

----------------------------------------------------------------------
Ran 1 test in 25.228s

FAILED (errors=1)
```

**Comment by ptnapoleon** [comment]
Fixed at c8e5b96078ab01f48faf3ebbda1b4d7ba5d426b2
