### ISSUE TITLE
Logs are not copied in all failure scenarios

### ISSUE THREAD

**Issue by EnigmaCurry** [riptano/cassandra-dtest#290]
http://cstar.datastax.com/tests/id/05524d18-fffd-11e4-8717-42010af0688f

That job obscured this error message, because it didn't copy the logs:

```
INFO  [main] 2015-05-21 14:05:22,588 CassandraDaemon.java:122 - JMX is enabled to receive remote connections on port: 7199
INFO  [main] 2015-05-21 14:05:22,613 CacheService.java:111 - Initializing key cache with capacity of 100 MBs.
INFO  [main] 2015-05-21 14:05:22,624 CacheService.java:133 - Initializing row cache with capacity of 0 MBs
INFO  [main] 2015-05-21 14:05:22,635 CacheService.java:150 - Initializing counter cache with capacity of 50 MBs
INFO  [main] 2015-05-21 14:05:22,638 CacheService.java:161 - Scheduling counter cache save to every 7200 seconds (going to save all keys).
INFO  [main] 2015-05-21 14:05:22,830 ColumnFamilyStore.java:314 - Initializing system.schema_triggers
ERROR [COMMIT-LOG-ALLOCATOR] 2015-05-21 14:05:24,462 CommitLog.java:397 - Failed managing commit log segments. Commit disk failure policy is stop; terminating thread
org.apache.cassandra.io.FSWriteError: java.io.IOException: Invalid argument
        at org.apache.cassandra.db.commitlog.CommitLogSegment.<init>(CommitLogSegment.java:177) ~[main/:na]
        at org.apache.cassandra.db.commitlog.CommitLogSegment.freshSegment(CommitLogSegment.java:119) ~[main/:na]
        at org.apache.cassandra.db.commitlog.CommitLogSegmentManager$1.runMayThrow(CommitLogSegmentManager.java:119) ~[main/:na]
        at org.apache.cassandra.utils.WrappedRunnable.run(WrappedRunnable.java:28) [main/:na]
        at java.lang.Thread.run(Thread.java:745) [na:1.7.0_76]
Caused by: java.io.IOException: Invalid argument
        at java.io.RandomAccessFile.setLength(Native Method) ~[na:1.7.0_76]
        at org.apache.cassandra.db.commitlog.CommitLogSegment.<init>(CommitLogSegment.java:163) ~[main/:na]
        ... 4 common frames omitted

```

**Comment by ptnapoleon** [comment]
Did you mean to file this to cstar perf?

**Comment by EnigmaCurry** [comment]
Yep :)
