### ISSUE TITLE
CCMError("Cannot find version") in "auth_test.py"

### ISSUE THREAD

**Issue by jasonstack** [riptano/cassandra-dtest#976]
Hi,

I am using Ubuntu 14.04 and cassandra-2.1.14 with latest Dtest

`
Failure: CCMError (Cannot find version) ... ERROR

======================================================================
ERROR: Failure: CCMError (Cannot find version)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/nose/loader.py", line 523, in makeTest
    return self._makeTest(obj, parent)
  File "/usr/local/lib/python2.7/dist-packages/nose/loader.py", line 570, in _makeTest
    return self.loadTestsFromTestCase(obj)
  File "/usr/local/lib/python2.7/dist-packages/nose/loader.py", line 494, in loadTestsFromTestCase
    return super(TestLoader, self).loadTestsFromTestCase(testCaseClass)
  File "/usr/lib/python2.7/unittest/loader.py", line 56, in loadTestsFromTestCase
    loaded_suite = self.suiteClass(map(testCaseClass, testCaseNames))
  File "/home/zhaoyang/cassandra-dtest/cassandra-dtest/auth_test.py", line 1000, in __init__
    if get_version_from_build(CASSANDRA_DIR) >= '3.0':
  File "build/bdist.linux-x86_64/egg/ccmlib/common.py", line 547, in get_version_from_build
    raise CCMError("Cannot find version")
CCMError: Cannot find version
`

**Comment by mambocab** [comment]
Thanks for the report. I've put a little time into trying to fix it over at #978; in theory, removing the dependency on the env var should fix it, but I haven't got it figured out on my machine. I'll put some more time into it if others don't see what I'm doing wrong in that PR.

**Comment by jasonstack** [comment]
Thank you Jim. May I ask some question about testing in Cassandra? the role of Dtest is for integreation test, is it?  How about Junit Test? I found that in 2.1.14, ant test is failing.. What's the criteria of releasing each version?

**Comment by mambocab** [comment]
@jasonstack Release is gated on a community vote, which happens on the `cassandra-dev` mailing list. [Here's a link](https://mail-archives.apache.org/mod_mbox/cassandra-dev/201604.mbox/%3CCALamAD+bamv=+cpb2Ccd2qvGTKkCz=q+b0HX5c1Eyt3vsjUfkQ@mail.gmail.com%3E) to where the vote for 2.1.14 started. Yes, the dtest suite is an integration suite; it's maintained by DataStax' Cassandra Test Engineering team. We produce a report with the results of the dtests and some performance tests for each release vote; you can find it linked in the email I linked above. The Cassandra devs own the unit test suite, so if you have questions about it, or more questions about the C\* release process, I think the #cassandra channel on freenode or the cassandra user mailing list would be better places to ask.

**Comment by chaitan64arun** [comment]
@mambocab I am wondering if #978 is finished?

**Comment by ptnapoleon** [comment]
My fault, yes, we'll merge today.

**Comment by mambocab** [comment]
@jasonstack @chaitan64arun Sorry for the delay, but it'll be at least another couple days before this is fixed -- I merged a fix that broke some of our failure-tracking code, we reverted it, and I have to debug that before this gets properly resolved.

**Comment by chaitan64arun** [comment]
@mambocab Thank you. I got it.
